counters:
  card_finishes_by_name:
    condition: "lambda card: card.get('name')"
    column_names:
      - Name
      - Count
    count_finishes: True

  card_finishes_by_set_name:
    condition: "lambda card: (card.get('set'), card.get('name'))"
    column_names:
      - Set
      - Name
      - Count
    count_finishes: True

  max_collector_number_by_set:
    condition: "lambda card: card.get('set')"
    max_field: collector_number
    column_names:
      - Set
      - Max Collector Number

  cards_by_name:
    condition: "lambda card: card.get('name')"
    column_names:
      - Name
      - Count
    count_finishes: False

  cards_by_set_name:
    condition: "lambda card: (card.get('set'), card.get('name'))"
    column_names:
      - Set
      - Name
      - Count
    count_finishes: False
